"$schema" = 'https://starship.rs/config-schema.json'

format = """\
[](mantle)\
$shell\
$username\
[](fg:mantle bg:blue)\
$directory\
[](fg:blue bg:teal)\
$git_branch\
$git_status\
[](fg:teal bg:mantle)\
$git_state\
[](fg:mantle)\
(    \
[](mantle)\
$status\
$cmd_duration\
$time\
[](fg:mantle))\
$line_break$sudo$character"""

palette = 'catppuccin_mocha'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[os]
disabled = false
style = "bg:blue fg:mantle"

[os.symbols]
Windows = "󰍲 "
Ubuntu = "󰕈 "
SUSE = " "
Raspbian = "󰐿 "
Mint = "󰣭 "
Macos = " "
Manjaro = " "
Linux = "󰌽 "
Gentoo = "󰣨 "
Fedora = "󰣛 "
Alpine = " "
Amazon = " "
Android = " "
Arch = "󰣇 "
Artix = "󰣇 "
CentOS = " "
Debian = "󰣚 "
Redhat = "󱄛 "
RedHatEnterprise = "󱄛 "

[shell]
fish_indicator = ' '
style = 'fg:text bg:mantle bold'
disabled = false
format = '[$indicator]($style)'

[username]
show_always = true
style_user = "bg:mantle fg:text bold"
style_root = "bg:mantle fg:text bold"
format = '[ $user ]($style)'

[directory]
style = "fg:mantle bg:blue bold"
repo_root_style = "fg:mantle bg:blue bold underline"
format = "[ $path ]($style)"
repo_root_format = "[ ]($style)[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[ ]($style)"
truncation_length = 3
truncation_symbol = "…/"
truncate_to_repo = false

[git_branch]
style = "fg:mantle bg:teal bold"
format = '[ $branch ]($style)'

[git_status]
conflicted = "󰳧 "
ahead = " "
behind = " "
diverged = "󱞿 "
up_to_date = ""
untracked = " "
stashed = "󱊖 "
modified = "󰜥 "
staged = " "
renamed = " "
deleted = " "
typechanged = ""
style = "fg:mantle bg:teal bold"
format = '[($all_status$ahead_behind)]($style)'

[git_state]
style = "fg:teal bg:mantle bold"
format ="[ $state( $progress_current/$progress_total) ]($style)"

[time]
disabled = false
time_format = "%R"
style = "fg:blue bg:mantle italic"
format = '[  $time]($style)'

[cmd_duration]
min_time = 500
format = '[  $duration ](italic fg:yellow bg:mantle)' 

[status]
style = 'fg:red bg:mantle italic'
symbol = ' '
format = '[$symbol $common_meaning$signal_name$maybe_int ]($style)'
disabled = false

[line_break]
disabled = false

[character]
format = " $symbol "
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[fill]
symbol = ' '

[sudo]
format = "[$symbol]($style)"
style = "fg:green bold"
symbol = "sudo"
disabled = false
